id = "InterDotRush"
name = "InterDotRush"
version = "1.0.0"
schema_version = 1
authors = ["Nikita Romanov"]
description = "InterDotRush for Zed"
repository = "https://github.com/JaneySprings/InterDotRush"

[language_servers.InterDotRush]
name = "InterDotRush"
languages = ["CSharp"]

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "dd5e59721a5f8dae34604060833902b882023aaf"
